---
# linted with yamllint
os: linux
language: go
go:
  - 1.12.12
env:
  global:
    - GOPROXY=https://proxy.golang.org
matrix:
  include:
    - language: python
      name: Check Boilerplate
      env:
        - TESTSUITE=boilerplate
      before_install:
        - pip install flake8 && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      script: make test

    - language: go
      name: Code Lint
      go: 1.12.12
      env:
        - TESTSUITE=lint
      before_install:
        - sudo apt-get install -y libvirt-dev
      script: make test

    - language: go
      name: Unit Test
      go: 1.12.12
      env:
        - TESTSUITE=unittest
      before_install:
        - sudo apt-get install -y libvirt-dev
      script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com?only=failed,errored
    on_success: never  # don't comment on successful builds.
    on_failure: always
    on_cancel: always
    on_error: always
