# Copyright 2018 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is where the pod that will download gvisor and restart the cluster will live

apiVersion: v1
kind: Pod
metadata: 
  name: gvisor
spec: 
  containers: 
    - name: "gvisor"
      image: "gcr.io/priya-wadhwa/gvisor:latest"
      args:
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /node/
        name: node
      - mountPath: /usr/libexec/sudo
        name: sudo
      - mountPath: /etc
        name: etc
      # - mountPath: /usr/lib
      #   name: usrlib
      - mountPath: /usr/share
        name: usrshare
      - mountPath: /tmp
        name: tmp
      - mountPath: /sys
        name: sys
      - mountPath: /mnt
        name: mnt
      - mountPath: /var/lib
        name: varlib
      env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/node/bin
  volumes:
  - name: node
    hostPath:
      # directory location on host
      path: /
  - name: sudo
    hostPath:
      # directory location on host
      path: /usr/libexec/sudo
  - name: etc
    hostPath:
      # directory location on host
      path: /etc
  - name: usrlib
    hostPath:
      # directory location on host
      path: /usr/lib
  - name: usrshare
    hostPath:
      # directory location on host
      path: /usr/share
  - name: tmp
    hostPath:
      # directory location on host
      path: /tmp
  - name: run
    hostPath:
      # directory location on host
      path: /run/systemd
  - name: sys
    hostPath:
      # directory location on host
      path: /sys
  - name: mnt
    hostPath:
      # directory location on host
      path: /mnt
  - name: varlib
    hostPath:
      # directory location on host
      path: /var/lib
  restartPolicy: Never

